appname="GeekDroid"
appver="1.4"
appcode="5"
packagename="github.znzsofficial.geekdroid"
theme="Theme_Material_Light_NoActionBar"
welcome_time="0"
debugmode=true
enableExtendedOutputSupport=false
enableDialogLog=false
user_permission={
  "INTERNET",
  "READ_EXTERNAL_STORAGE",
  "WRITE_EXTERNAL_STORAGE"
}
